language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libzmq3-dev
# command to install dependencies
install: "pip install -e ."
# command to run tests
script: nosetests
